# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Docker Setup Buildx'
description: 'Set up Docker Buildx'
author: 'docker'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  version:
    description: 'Buildx version. e.g. v0.3.0'
    required: false
  driver:
    description: 'Sets the builder driver to be used'
    default: 'docker-container'
    required: false
  driver-opt:
    description: 'Passes additional driver-specific options. Eg. image=moby/buildkit:master'
    required: false
  buildkitd-flags:
    description: 'Flags for buildkitd daemon'
    required: false
  install:
    description: 'Sets up docker build command as an alias to docker buildx'
    default: 'false'
    required: false
  use:
    description: 'Switch to this builder instance'
    default: 'true'
    required: false

outputs:
  name:
    description: 'Builder instance name'
  platforms:
    description: 'Available platforms (comma separated)'

runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
