# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Docker Setup Buildx'
description: 'Set up Docker Buildx'
author: 'docker'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  version:
    description: 'Buildx version. (eg. v0.3.0)'
    required: false
  driver:
    description: 'Sets the builder driver to be used'
    default: 'docker-container'
    required: false
  driver-opts:
    description: 'List of additional driver-specific options. (eg. image=moby/buildkit:master)'
    required: false
  buildkitd-flags:
    description: 'Flags for buildkitd daemon'
    default: '--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host'
    required: false
  install:
    description: 'Sets up docker build command as an alias to docker buildx'
    default: 'false'
    required: false
  use:
    description: 'Switch to this builder instance'
    default: 'true'
    required: false
  context:
    description: 'Name of a context from docker context ls or an endpoint as the address for docker socket (eg. DOCKER_HOST value)'
    required: false

outputs:
  name:
    description: 'Builder instance name'
  platforms:
    description: 'Available platforms (comma separated)'

runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
